image: "ruby:2.7"

.tests:
  stage: test
  only:
    refs:
      - master
      - tags
      - merge_requests

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v  # Print out ruby version for debugging
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

rubocop:
  extends: .tests
  script:
    - bundle exec rubocop

rspec:
  extends: .tests
  image: "ruby:$RUBY_VERSION"
  script:
    - bundle exec rspec
  parallel:
    matrix:
      - RUBY_VERSION:
        - "2.7"
        - "3.0"

danger-review:
  extends: .tests
  needs: []
  script:
    - >
      if [ -z "$DANGER_GITLAB_API_TOKEN" ]; then
        # Force danger to skip CI source GitLab and fallback to "local only git repo".
        unset GITLAB_CI
        # We need to base SHA to help danger determine the base commit for this shallow clone.
        bundle exec danger dry_run --fail-on-errors=true --verbose --base="$CI_MERGE_REQUEST_DIFF_BASE_SHA"
      else
        bundle exec danger --fail-on-errors=true --verbose
      fi
