image: "ruby:2.7"

.tests:
  stage: test
  only:
    refs:
      - master
      - tags
      - merge_requests

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v  # Print out ruby version for debugging
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

rubocop:
  extends: .tests
  script:
    - bundle exec rubocop

rspec:
  extends: .tests
  image: "ruby:$RUBY_VERSION"
  script:
    - bundle exec rspec
  parallel:
    matrix:
      - RUBY_VERSION:
        - "2.7"
        - "3.0"

danger-review:
  stage: test
  rules:
    - if: '$DANGER_GITLAB_API_TOKEN && $CI_MERGE_REQUEST_IID'
  needs: []
  script:
    - bundle exec danger --fail-on-errors=true --verbose
